name: pets_shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  image_picker: ^1.1.2
  flutter_custom_clippers: ^2.1.0
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: SfProMedium
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
    - family: SfProRegular
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf